// SPDX-License-Identifier: LGPL-3.0-or-later
// Copyright (C) 2026 s7commplus-rs contributors
//
// The curve parameters and the x-only ladder formulation follow `gijzelaerr/s7commplus`
// (`s7commplus/v1_session_key/real_plc/curve.py`, MIT), which identified HarpoS7's
// `SeedTransform` monoliths (`bonk-dev/HarpoS7`, MIT) as this scalar multiplication.
// See `LICENSE-HarpoS7` and `LICENSE-gijzelaerr-s7commplus`.

//! The elliptic curve behind the real-PLC `SeedTransform`: `y² = x³ − x + B` over
//! `GF(p)`, `p = 2¹⁶⁰ − 47`, whose group has prime order [`ORDER`].
//!
//! `SeedTransform` is an x-only ECDH on it: the ephemeral `x(k·G)` goes into the blob and the
//! shared `x(k·PublicKey)` keys the seed mask. Only x-coordinates are ever needed, so
//! [`x_multiply`] is a Montgomery ladder on `(X : Z)` coordinates.

/// A field element of `GF(2¹⁶⁰ − 47)`: five little-endian 32-bit limbs, always reduced.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
struct Fe([u32; 5]);

/// `p = 2¹⁶⁰ − 47`.
const P: Fe = Fe([
    0xFFFF_FFD1,
    0xFFFF_FFFF,
    0xFFFF_FFFF,
    0xFFFF_FFFF,
    0xFFFF_FFFF,
]);
const ZERO: Fe = Fe([0; 5]);
const ONE: Fe = Fe([1, 0, 0, 0, 0]);

/// The curve's `B` coefficient (`A = −1`).
const B: Fe = fe_from_be_hex("FDEC56A0F1A148A7CA6F04463A24F5F56C3F3A4F");

/// Affine x of the generator `G` (HarpoS7's `Transform7Data[0xD8..0xEC]`, little endian).
pub const GENERATOR_X: [u8; 20] = le_bytes_from_be_hex("7D2ED8E2846E58D74A7A613285471707A39D0C8E");

/// The scalar mask: `SeedTransform`'s ladder walks `prng2 ⊕ SCALAR_MASK` (both little endian).
pub const SCALAR_MASK: [u8; 20] = le_bytes_from_be_hex("F8E62E8673B79CA477A1D36333B1C0DE6C706448");

/// The (prime) order of the group generated by `G`, little endian (161 bits).
#[cfg(test)]
pub const ORDER: [u8; 21] = {
    let mut out = [0u8; 21];
    let low = le_bytes_from_be_hex("00000000000000000000F368CDA5CDB2EBFC69C7");
    let mut i = 0;
    while i < 20 {
        out[i] = low[i];
        i += 1;
    }
    out[20] = 1;
    out
};

const fn hex_nibble(c: u8) -> u8 {
    match c {
        b'0'..=b'9' => c - b'0',
        b'A'..=b'F' => c - b'A' + 10,
        b'a'..=b'f' => c - b'a' + 10,
        _ => panic!("bad hex digit"),
    }
}

/// 40 big-endian hex digits as 20 little-endian bytes.
const fn le_bytes_from_be_hex(hex: &str) -> [u8; 20] {
    let h = hex.as_bytes();
    assert!(h.len() == 40);
    let mut out = [0u8; 20];
    let mut i = 0;
    while i < 20 {
        out[19 - i] = hex_nibble(h[2 * i]) << 4 | hex_nibble(h[2 * i + 1]);
        i += 1;
    }
    out
}

const fn fe_from_be_hex(hex: &str) -> Fe {
    let b = le_bytes_from_be_hex(hex);
    let mut limbs = [0u32; 5];
    let mut i = 0;
    while i < 5 {
        limbs[i] = u32::from_le_bytes([b[4 * i], b[4 * i + 1], b[4 * i + 2], b[4 * i + 3]]);
        i += 1;
    }
    Fe(limbs)
}

impl Fe {
    /// Read 20 little-endian bytes, reducing modulo `p`.
    fn from_le_bytes(b: &[u8; 20]) -> Fe {
        let mut limbs = [0u32; 5];
        for (i, limb) in limbs.iter_mut().enumerate() {
            *limb = u32::from_le_bytes(b[4 * i..4 * i + 4].try_into().unwrap());
        }
        Fe(limbs).reduce_once()
    }

    fn to_le_bytes(self) -> [u8; 20] {
        let mut out = [0u8; 20];
        for (i, limb) in self.0.iter().enumerate() {
            out[4 * i..4 * i + 4].copy_from_slice(&limb.to_le_bytes());
        }
        out
    }

    fn is_zero(self) -> bool {
        self.0 == [0; 5]
    }

    fn ge_p(self) -> bool {
        for i in (0..5).rev() {
            if self.0[i] != P.0[i] {
                return self.0[i] > P.0[i];
            }
        }
        true
    }

    /// Subtract `p` once if the value is `≥ p` (inputs here are always `< 2p`).
    fn reduce_once(self) -> Fe {
        if self.ge_p() {
            sub_raw(self, P).0
        } else {
            self
        }
    }

    fn add(self, o: Fe) -> Fe {
        let mut out = [0u32; 5];
        let mut carry = 0u64;
        for (i, slot) in out.iter_mut().enumerate() {
            let s = u64::from(self.0[i]) + u64::from(o.0[i]) + carry;
            *slot = s as u32;
            carry = s >> 32;
        }
        if carry != 0 {
            // 2¹⁶⁰ ≡ 47: the true sum is out + 2¹⁶⁰ < 2p, so out + 47 < p and cannot carry.
            add_small(Fe(out), 47)
        } else {
            Fe(out).reduce_once()
        }
    }

    fn sub(self, o: Fe) -> Fe {
        let (diff, borrow) = sub_raw(self, o);
        if borrow {
            // diff = self − o + 2¹⁶⁰; adding p − 2¹⁶⁰ = −47 means subtracting 47.
            sub_raw(diff, Fe([47, 0, 0, 0, 0])).0
        } else {
            diff
        }
    }

    fn mul(self, o: Fe) -> Fe {
        // Schoolbook 5×5 limbs into a 320-bit product.
        let mut wide = [0u64; 10];
        for i in 0..5 {
            let mut carry = 0u64;
            for j in 0..5 {
                let t = u64::from(self.0[i]) * u64::from(o.0[j]) + wide[i + j] + carry;
                wide[i + j] = t & 0xFFFF_FFFF;
                carry = t >> 32;
            }
            wide[i + 5] = carry;
        }
        // Fold the high 160 bits down with 2¹⁶⁰ ≡ 47 (twice), then reduce.
        let mut t = [0u64; 6];
        let mut carry = 0u64;
        for i in 0..5 {
            let s = wide[i] + 47 * wide[i + 5] + carry;
            t[i] = s & 0xFFFF_FFFF;
            carry = s >> 32;
        }
        t[5] = carry;
        let mut limbs = [0u32; 5];
        let mut carry = 47 * t[5];
        for i in 0..5 {
            let s = t[i] + carry;
            limbs[i] = s as u32;
            carry = s >> 32;
        }
        let r = Fe(limbs);
        if carry != 0 {
            add_small(r, 47)
        } else {
            r.reduce_once()
        }
    }

    fn square(self) -> Fe {
        self.mul(self)
    }

    fn small(n: u32) -> Fe {
        Fe([n, 0, 0, 0, 0])
    }

    /// `self^(p−2)`, the inverse of a nonzero element (Fermat).
    fn invert(self) -> Fe {
        // p − 2 = 2¹⁶⁰ − 49, scanned from the top bit.
        let e = sub_raw(P, Fe::small(2)).0;
        let mut acc = ONE;
        for i in (0..160).rev() {
            acc = acc.square();
            if (e.0[i / 32] >> (i % 32)) & 1 == 1 {
                acc = acc.mul(self);
            }
        }
        acc
    }
}

/// `a − b` over 160 bits, with the borrow out.
fn sub_raw(a: Fe, b: Fe) -> (Fe, bool) {
    let mut out = [0u32; 5];
    let mut borrow = 0i64;
    for (i, slot) in out.iter_mut().enumerate() {
        let d = i64::from(a.0[i]) - i64::from(b.0[i]) - borrow;
        *slot = d as u32;
        borrow = i64::from(d < 0);
    }
    (Fe(out), borrow != 0)
}

/// `a + n` for a small `n`, reduced (callers guarantee the result is `< 2p`).
fn add_small(a: Fe, n: u32) -> Fe {
    a.add(Fe::small(n))
}

/// `(X : Z)` projective x-coordinate; `Z = 0` is the point at infinity.
type Xz = (Fe, Fe);

/// `x(2·Q)` with `A = −1`: `X = (X² + Z²)² − 8B·X·Z³`, `Z = 4Z·(X³ − X·Z² + B·Z³)`.
fn double((x, z): Xz) -> Xz {
    let xx = x.square();
    let zz = z.square();
    let xz = x.mul(z);
    let x_out = xx.add(zz).square().sub(Fe::small(8).mul(B).mul(xz).mul(zz));
    let inner = x.mul(xx).sub(x.mul(zz)).add(B.mul(z).mul(zz));
    (x_out, Fe::small(4).mul(z).mul(inner))
}

/// `x(Q1 + Q2)` from `x(Q1)`, `x(Q2)` and the affine `x(Q1 − Q2)` (`A = −1`).
fn add_diff((x1, z1): Xz, (x2, z2): Xz, difference: Fe) -> Xz {
    let x1z2 = x1.mul(z2);
    let x2z1 = x2.mul(z1);
    let z1z2 = z1.mul(z2);
    let cross = x1z2.sub(x2z1);
    let cross2 = cross.square();
    let x_out = Fe::small(2)
        .mul(x1z2.add(x2z1))
        .mul(x1.mul(x2).sub(z1z2))
        .add(Fe::small(4).mul(B).mul(z1z2.square()))
        .sub(difference.mul(cross2));
    (x_out, cross2)
}

/// Affine `x(k·Q)` for the point `Q` with affine x-coordinate `x` (both 20 bytes little
/// endian), or all zeros for the point at infinity. The ladder always walks all 160 bits of
/// `k`, like the original; leading zero bits simply leave it at infinity.
///
/// `Q` may lie on the curve or on its quadratic twist: the x-only formulas are the same.
pub fn x_multiply(scalar: &[u8; 20], x: &[u8; 20]) -> [u8; 20] {
    let xq = Fe::from_le_bytes(x);
    let mut low: Xz = (ONE, ZERO); // infinity
    let mut high: Xz = (xq, ONE); // Q; high − low = Q throughout
    for i in (0..160).rev() {
        let total = add_diff(low, high, xq);
        if (scalar[i / 8] >> (i % 8)) & 1 == 1 {
            low = total;
            high = double(high);
        } else {
            low = double(low);
            high = total;
        }
    }
    let (x_out, z_out) = low;
    if z_out.is_zero() {
        [0u8; 20]
    } else {
        x_out.mul(z_out.invert()).to_le_bytes()
    }
}

/// The scalar `SeedTransform`'s ladder walks for a 20-byte `prng2`.
pub fn ladder_scalar(prng2: &[u8; 20]) -> [u8; 20] {
    let mut k = *prng2;
    for (b, m) in k.iter_mut().zip(SCALAR_MASK) {
        *b ^= m;
    }
    k
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Generator y (test-only: the affine reference arithmetic needs it).
    const GENERATOR_Y: Fe = fe_from_be_hex("57A735E99D694CFE6C7FE8F788BCF113CD8C673B");

    fn gx() -> Fe {
        Fe::from_le_bytes(&GENERATOR_X)
    }

    /// Independent affine reference: `None` is infinity.
    type Pt = Option<(Fe, Fe)>;

    fn affine_add(p: Pt, q: Pt) -> Pt {
        let (Some((x1, y1)), Some((x2, y2))) = (p, q) else {
            return p.or(q);
        };
        let lambda = if x1 == x2 {
            if y1.add(y2).is_zero() {
                return None;
            }
            // (3x² + A) / 2y, A = −1
            Fe::small(3)
                .mul(x1.square())
                .sub(ONE)
                .mul(Fe::small(2).mul(y1).invert())
        } else {
            y2.sub(y1).mul(x2.sub(x1).invert())
        };
        let x3 = lambda.square().sub(x1).sub(x2);
        let y3 = lambda.mul(x1.sub(x3)).sub(y1);
        Some((x3, y3))
    }

    fn affine_mul(k: u128, p: Pt) -> Pt {
        let mut acc = None;
        for i in (0..128).rev() {
            acc = affine_add(acc, acc);
            if (k >> i) & 1 == 1 {
                acc = affine_add(acc, p);
            }
        }
        acc
    }

    fn scalar_u64(k: u64) -> [u8; 20] {
        let mut s = [0u8; 20];
        s[..8].copy_from_slice(&k.to_le_bytes());
        s
    }

    #[test]
    fn field_inverse_and_reduction() {
        let a = fe_from_be_hex("0123456789ABCDEF0123456789ABCDEF01234567");
        assert_eq!(a.mul(a.invert()), ONE);
        // p − 1 + 1 wraps to 0; 0 − 1 is p − 1.
        let pm1 = sub_raw(P, ONE).0;
        assert_eq!(pm1.add(ONE), ZERO);
        assert_eq!(ZERO.sub(ONE), pm1);
        assert_eq!(pm1.mul(pm1), ONE); // (−1)² = 1
    }

    #[test]
    fn generator_is_on_the_curve() {
        let x = gx();
        let rhs = x.square().mul(x).sub(x).add(B);
        assert_eq!(GENERATOR_Y.square(), rhs);
    }

    #[test]
    fn ladder_matches_affine_reference() {
        let g = Some((gx(), GENERATOR_Y));
        for k in [1u64, 2, 3, 5, 7, 0xFF, 0x1234_5678, u64::MAX] {
            let expected = affine_mul(u128::from(k), g).map_or([0u8; 20], |(x, _)| x.to_le_bytes());
            assert_eq!(
                x_multiply(&scalar_u64(k), &GENERATOR_X),
                expected,
                "k = {k:#x}"
            );
        }
        assert_eq!(x_multiply(&scalar_u64(0), &GENERATOR_X), [0u8; 20]);
    }

    #[test]
    fn generator_has_the_claimed_prime_order() {
        // ORDER = 2¹⁶⁰ + C (C is 80 bits), so ORDER·G = ∞ ⇔ 2¹⁶⁰·G = −(C·G), checked with the
        // independent affine arithmetic.
        const C: u128 = 0xF368_CDA5_CDB2_EBFC_69C7;
        let mut c_le = [0u8; 20];
        c_le[..16].copy_from_slice(&C.to_le_bytes());
        let mut order_low = [0u8; 20];
        order_low.copy_from_slice(&ORDER[..20]);
        assert_eq!(order_low, c_le);
        assert_eq!(ORDER[20], 1);

        let g = Some((gx(), GENERATOR_Y));
        let mut two160 = g;
        for _ in 0..160 {
            two160 = affine_add(two160, two160);
        }
        let (cx, cy) = affine_mul(C, g).unwrap();
        let (tx, ty) = two160.unwrap();
        assert_eq!((tx, ty), (cx, ZERO.sub(cy)));
        // The ladder agrees with the affine reference on this 80-bit scalar too.
        assert_eq!(x_multiply(&c_le, &GENERATOR_X), cx.to_le_bytes());
    }

    #[test]
    fn scalar_mask_is_applied_bytewise() {
        let k = ladder_scalar(&[0u8; 20]);
        assert_eq!(k, SCALAR_MASK);
        assert_eq!(ladder_scalar(&SCALAR_MASK), [0u8; 20]);
    }
}
